package com.wisdom.dao.mapper.vfs;

import com.wisdom.dao.entity.vfs.FileUploadRecord;
import com.wisdom.dao.entity.vfs.FileUploadRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileUploadRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int countByExample(FileUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int deleteByExample(FileUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long busiSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int insert(FileUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int insertSelective(FileUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    List<FileUploadRecord> selectByExample(FileUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    FileUploadRecord selectByPrimaryKey(Long busiSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FileUploadRecord record, @Param("example") FileUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FileUploadRecord record, @Param("example") FileUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    void insertBatch(List<FileUploadRecord> recordLst);
}